version: '3.3'
services:
  sync:
    build: .
    volumes:
     - type: bind
       source: ./
       target: /root/app
    command: -vvv
    environment:
      - MAILCHIMP_API_KEY
      - MAILCHIMP_LIST_ID
      - OMETRIA_ENDPOINT
      - OMETRIA_API_KEY